# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 醉了做美梦，醒了敲代码 - lvdingjin的博客
email: lvdingjinldj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  穷极一生去做一件美好的事情。
baseurl: "https://lvdingjin.github.io" # the subpath of your site, e.g. /blog
url: "https://lvdingjin.github.io" # the base hostname & protocol for your site
twitter_username: # waiting #
github_username:  lvdingjin

# Build settings
markdown: kramdown
